import * as Blockly from "blockly";

// Block for setting pib's eyes on the display to one of the standard
// emotions (rendered as animated GIFs by the display ROS-node; the
// graphics are generated by display/static_images/generate_emotion_eyes.py)
// OR to a user-created custom facial expression (see the "Gesichtsausdruecke
// verwalten" page). The dropdown is built imperatively (like play_wav's
// FILENAME field) so the custom-expression options can be refreshed at
// runtime - see program-workspace.component.ts's updateEmotionBlockDropdown,
// mirroring updatePlayWavBlockDropdown for uploaded wav files. Custom
// expression values are prefixed "CUSTOM:<expressionId>" so the generator
// (function-declarations.ts) can tell them apart from the fixed emotions.
export const display_blocks = (Blockly.Blocks["set_eyes_emotion"] = {
    init() {
        this.appendDummyInput()
            .appendField(
                (Blockly.Msg["PIB_SET_EYES"] || "set eyes to  %1").replace(
                    "%1",
                    "",
                ),
            )
            .appendField(
                new CustomFieldDropdown(this.getEmotions),
                "EMOTION",
            );
        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
        this.setColour(200);
        this.setTooltip(
            Blockly.Msg["PIB_SET_EYES_TOOLTIP"] ||
                "sets pib's eyes on the display to the chosen emotion",
        );
        this.setHelpUrl("");
    },

    // Overwritten at runtime with the fixed emotions plus any custom
    // facial expressions (see updateEmotionBlockDropdown) - this default
    // only matters for the compile-server copy, which never renders a
    // live dropdown (see play-wav-block.ts's comment for the same reason).
    getEmotions() {
        return [
            [Blockly.Msg["PIB_EYES_NEUTRAL"] || "neutral", "NEUTRAL"],
            [Blockly.Msg["PIB_EYES_HAPPY"] || "happy", "HAPPY"],
            [Blockly.Msg["PIB_EYES_SAD"] || "sad", "SAD"],
            [Blockly.Msg["PIB_EYES_ANGRY"] || "angry", "ANGRY"],
            [Blockly.Msg["PIB_EYES_SURPRISED"] || "surprised", "SURPRISED"],
            [Blockly.Msg["PIB_EYES_SLEEPY"] || "sleepy", "SLEEPY"],
            [Blockly.Msg["PIB_EYES_HEART"] || "in love", "HEART"],
            [Blockly.Msg["PIB_EYES_STAR"] || "star-struck", "STAR"],
            [Blockly.Msg["PIB_EYES_COOL"] || "cool", "COOL"],
            [Blockly.Msg["PIB_EYES_WINK"] || "wink", "WINK"],
        ];
    },
});

class CustomFieldDropdown extends Blockly.FieldDropdown {
    constructor(menuGenerator: any, opt_validator?: any, opt_config?: any) {
        super(menuGenerator, opt_validator, opt_config);
    }
    override doClassValidation_(newValue: any) {
        return newValue;
    }
}
